/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariosRouteImport } from './routes/voluntarios'
import { Route as RegistrarCentroRouteImport } from './routes/registrar-centro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NecesidadesRouteImport } from './routes/necesidades'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as CentrosRouteImport } from './routes/centros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelVoluntarioRouteImport } from './routes/panel.voluntario'
import { Route as PanelTransportistaRouteImport } from './routes/panel.transportista'
import { Route as PanelOngRouteImport } from './routes/panel.ong'
import { Route as PanelEmpresaRouteImport } from './routes/panel.empresa'
import { Route as PanelDonadorRouteImport } from './routes/panel.donador'
import { Route as PanelDiasporaRouteImport } from './routes/panel.diaspora'
import { Route as PanelCentroRouteImport } from './routes/panel.centro'
import { Route as PanelAutoridadRouteImport } from './routes/panel.autoridad'
import { Route as PanelAdminRouteImport } from './routes/panel.admin'
import { Route as CentroIdRouteImport } from './routes/centro.$id'

const VoluntariosRoute = VoluntariosRouteImport.update({
  id: '/voluntarios',
  path: '/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarCentroRoute = RegistrarCentroRouteImport.update({
  id: '/registrar-centro',
  path: '/registrar-centro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NecesidadesRoute = NecesidadesRouteImport.update({
  id: '/necesidades',
  path: '/necesidades',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrosRoute = CentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelVoluntarioRoute = PanelVoluntarioRouteImport.update({
  id: '/panel/voluntario',
  path: '/panel/voluntario',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelTransportistaRoute = PanelTransportistaRouteImport.update({
  id: '/panel/transportista',
  path: '/panel/transportista',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelOngRoute = PanelOngRouteImport.update({
  id: '/panel/ong',
  path: '/panel/ong',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelEmpresaRoute = PanelEmpresaRouteImport.update({
  id: '/panel/empresa',
  path: '/panel/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelDonadorRoute = PanelDonadorRouteImport.update({
  id: '/panel/donador',
  path: '/panel/donador',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelDiasporaRoute = PanelDiasporaRouteImport.update({
  id: '/panel/diaspora',
  path: '/panel/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelCentroRoute = PanelCentroRouteImport.update({
  id: '/panel/centro',
  path: '/panel/centro',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAutoridadRoute = PanelAutoridadRouteImport.update({
  id: '/panel/autoridad',
  path: '/panel/autoridad',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/panel/admin',
  path: '/panel/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroIdRoute = CentroIdRouteImport.update({
  id: '/centro/$id',
  path: '/centro/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/impacto': typeof ImpactoRoute
  '/marca': typeof MarcaRoute
  '/necesidades': typeof NecesidadesRoute
  '/onboarding': typeof OnboardingRoute
  '/registrar-centro': typeof RegistrarCentroRoute
  '/voluntarios': typeof VoluntariosRoute
  '/centro/$id': typeof CentroIdRoute
  '/panel/admin': typeof PanelAdminRoute
  '/panel/autoridad': typeof PanelAutoridadRoute
  '/panel/centro': typeof PanelCentroRoute
  '/panel/diaspora': typeof PanelDiasporaRoute
  '/panel/donador': typeof PanelDonadorRoute
  '/panel/empresa': typeof PanelEmpresaRoute
  '/panel/ong': typeof PanelOngRoute
  '/panel/transportista': typeof PanelTransportistaRoute
  '/panel/voluntario': typeof PanelVoluntarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/impacto': typeof ImpactoRoute
  '/marca': typeof MarcaRoute
  '/necesidades': typeof NecesidadesRoute
  '/onboarding': typeof OnboardingRoute
  '/registrar-centro': typeof RegistrarCentroRoute
  '/voluntarios': typeof VoluntariosRoute
  '/centro/$id': typeof CentroIdRoute
  '/panel/admin': typeof PanelAdminRoute
  '/panel/autoridad': typeof PanelAutoridadRoute
  '/panel/centro': typeof PanelCentroRoute
  '/panel/diaspora': typeof PanelDiasporaRoute
  '/panel/donador': typeof PanelDonadorRoute
  '/panel/empresa': typeof PanelEmpresaRoute
  '/panel/ong': typeof PanelOngRoute
  '/panel/transportista': typeof PanelTransportistaRoute
  '/panel/voluntario': typeof PanelVoluntarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/impacto': typeof ImpactoRoute
  '/marca': typeof MarcaRoute
  '/necesidades': typeof NecesidadesRoute
  '/onboarding': typeof OnboardingRoute
  '/registrar-centro': typeof RegistrarCentroRoute
  '/voluntarios': typeof VoluntariosRoute
  '/centro/$id': typeof CentroIdRoute
  '/panel/admin': typeof PanelAdminRoute
  '/panel/autoridad': typeof PanelAutoridadRoute
  '/panel/centro': typeof PanelCentroRoute
  '/panel/diaspora': typeof PanelDiasporaRoute
  '/panel/donador': typeof PanelDonadorRoute
  '/panel/empresa': typeof PanelEmpresaRoute
  '/panel/ong': typeof PanelOngRoute
  '/panel/transportista': typeof PanelTransportistaRoute
  '/panel/voluntario': typeof PanelVoluntarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centros'
    | '/impacto'
    | '/marca'
    | '/necesidades'
    | '/onboarding'
    | '/registrar-centro'
    | '/voluntarios'
    | '/centro/$id'
    | '/panel/admin'
    | '/panel/autoridad'
    | '/panel/centro'
    | '/panel/diaspora'
    | '/panel/donador'
    | '/panel/empresa'
    | '/panel/ong'
    | '/panel/transportista'
    | '/panel/voluntario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centros'
    | '/impacto'
    | '/marca'
    | '/necesidades'
    | '/onboarding'
    | '/registrar-centro'
    | '/voluntarios'
    | '/centro/$id'
    | '/panel/admin'
    | '/panel/autoridad'
    | '/panel/centro'
    | '/panel/diaspora'
    | '/panel/donador'
    | '/panel/empresa'
    | '/panel/ong'
    | '/panel/transportista'
    | '/panel/voluntario'
  id:
    | '__root__'
    | '/'
    | '/centros'
    | '/impacto'
    | '/marca'
    | '/necesidades'
    | '/onboarding'
    | '/registrar-centro'
    | '/voluntarios'
    | '/centro/$id'
    | '/panel/admin'
    | '/panel/autoridad'
    | '/panel/centro'
    | '/panel/diaspora'
    | '/panel/donador'
    | '/panel/empresa'
    | '/panel/ong'
    | '/panel/transportista'
    | '/panel/voluntario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentrosRoute: typeof CentrosRoute
  ImpactoRoute: typeof ImpactoRoute
  MarcaRoute: typeof MarcaRoute
  NecesidadesRoute: typeof NecesidadesRoute
  OnboardingRoute: typeof OnboardingRoute
  RegistrarCentroRoute: typeof RegistrarCentroRoute
  VoluntariosRoute: typeof VoluntariosRoute
  CentroIdRoute: typeof CentroIdRoute
  PanelAdminRoute: typeof PanelAdminRoute
  PanelAutoridadRoute: typeof PanelAutoridadRoute
  PanelCentroRoute: typeof PanelCentroRoute
  PanelDiasporaRoute: typeof PanelDiasporaRoute
  PanelDonadorRoute: typeof PanelDonadorRoute
  PanelEmpresaRoute: typeof PanelEmpresaRoute
  PanelOngRoute: typeof PanelOngRoute
  PanelTransportistaRoute: typeof PanelTransportistaRoute
  PanelVoluntarioRoute: typeof PanelVoluntarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntarios': {
      id: '/voluntarios'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar-centro': {
      id: '/registrar-centro'
      path: '/registrar-centro'
      fullPath: '/registrar-centro'
      preLoaderRoute: typeof RegistrarCentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necesidades': {
      id: '/necesidades'
      path: '/necesidades'
      fullPath: '/necesidades'
      preLoaderRoute: typeof NecesidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centros': {
      id: '/centros'
      path: '/centros'
      fullPath: '/centros'
      preLoaderRoute: typeof CentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/voluntario': {
      id: '/panel/voluntario'
      path: '/panel/voluntario'
      fullPath: '/panel/voluntario'
      preLoaderRoute: typeof PanelVoluntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/transportista': {
      id: '/panel/transportista'
      path: '/panel/transportista'
      fullPath: '/panel/transportista'
      preLoaderRoute: typeof PanelTransportistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/ong': {
      id: '/panel/ong'
      path: '/panel/ong'
      fullPath: '/panel/ong'
      preLoaderRoute: typeof PanelOngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/empresa': {
      id: '/panel/empresa'
      path: '/panel/empresa'
      fullPath: '/panel/empresa'
      preLoaderRoute: typeof PanelEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/donador': {
      id: '/panel/donador'
      path: '/panel/donador'
      fullPath: '/panel/donador'
      preLoaderRoute: typeof PanelDonadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/diaspora': {
      id: '/panel/diaspora'
      path: '/panel/diaspora'
      fullPath: '/panel/diaspora'
      preLoaderRoute: typeof PanelDiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/centro': {
      id: '/panel/centro'
      path: '/panel/centro'
      fullPath: '/panel/centro'
      preLoaderRoute: typeof PanelCentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/autoridad': {
      id: '/panel/autoridad'
      path: '/panel/autoridad'
      fullPath: '/panel/autoridad'
      preLoaderRoute: typeof PanelAutoridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/admin': {
      id: '/panel/admin'
      path: '/panel/admin'
      fullPath: '/panel/admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro/$id': {
      id: '/centro/$id'
      path: '/centro/$id'
      fullPath: '/centro/$id'
      preLoaderRoute: typeof CentroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentrosRoute: CentrosRoute,
  ImpactoRoute: ImpactoRoute,
  MarcaRoute: MarcaRoute,
  NecesidadesRoute: NecesidadesRoute,
  OnboardingRoute: OnboardingRoute,
  RegistrarCentroRoute: RegistrarCentroRoute,
  VoluntariosRoute: VoluntariosRoute,
  CentroIdRoute: CentroIdRoute,
  PanelAdminRoute: PanelAdminRoute,
  PanelAutoridadRoute: PanelAutoridadRoute,
  PanelCentroRoute: PanelCentroRoute,
  PanelDiasporaRoute: PanelDiasporaRoute,
  PanelDonadorRoute: PanelDonadorRoute,
  PanelEmpresaRoute: PanelEmpresaRoute,
  PanelOngRoute: PanelOngRoute,
  PanelTransportistaRoute: PanelTransportistaRoute,
  PanelVoluntarioRoute: PanelVoluntarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
