/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariosRouteImport } from './routes/voluntarios'
import { Route as RegistrarCentroRouteImport } from './routes/registrar-centro'
import { Route as NecesidadesRouteImport } from './routes/necesidades'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as CentrosRouteImport } from './routes/centros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentroIdRouteImport } from './routes/centro.$id'

const VoluntariosRoute = VoluntariosRouteImport.update({
  id: '/voluntarios',
  path: '/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarCentroRoute = RegistrarCentroRouteImport.update({
  id: '/registrar-centro',
  path: '/registrar-centro',
  getParentRoute: () => rootRouteImport,
} as any)
const NecesidadesRoute = NecesidadesRouteImport.update({
  id: '/necesidades',
  path: '/necesidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrosRoute = CentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroIdRoute = CentroIdRouteImport.update({
  id: '/centro/$id',
  path: '/centro/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/impacto': typeof ImpactoRoute
  '/necesidades': typeof NecesidadesRoute
  '/registrar-centro': typeof RegistrarCentroRoute
  '/voluntarios': typeof VoluntariosRoute
  '/centro/$id': typeof CentroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/impacto': typeof ImpactoRoute
  '/necesidades': typeof NecesidadesRoute
  '/registrar-centro': typeof RegistrarCentroRoute
  '/voluntarios': typeof VoluntariosRoute
  '/centro/$id': typeof CentroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/impacto': typeof ImpactoRoute
  '/necesidades': typeof NecesidadesRoute
  '/registrar-centro': typeof RegistrarCentroRoute
  '/voluntarios': typeof VoluntariosRoute
  '/centro/$id': typeof CentroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centros'
    | '/impacto'
    | '/necesidades'
    | '/registrar-centro'
    | '/voluntarios'
    | '/centro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centros'
    | '/impacto'
    | '/necesidades'
    | '/registrar-centro'
    | '/voluntarios'
    | '/centro/$id'
  id:
    | '__root__'
    | '/'
    | '/centros'
    | '/impacto'
    | '/necesidades'
    | '/registrar-centro'
    | '/voluntarios'
    | '/centro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentrosRoute: typeof CentrosRoute
  ImpactoRoute: typeof ImpactoRoute
  NecesidadesRoute: typeof NecesidadesRoute
  RegistrarCentroRoute: typeof RegistrarCentroRoute
  VoluntariosRoute: typeof VoluntariosRoute
  CentroIdRoute: typeof CentroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntarios': {
      id: '/voluntarios'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar-centro': {
      id: '/registrar-centro'
      path: '/registrar-centro'
      fullPath: '/registrar-centro'
      preLoaderRoute: typeof RegistrarCentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necesidades': {
      id: '/necesidades'
      path: '/necesidades'
      fullPath: '/necesidades'
      preLoaderRoute: typeof NecesidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centros': {
      id: '/centros'
      path: '/centros'
      fullPath: '/centros'
      preLoaderRoute: typeof CentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro/$id': {
      id: '/centro/$id'
      path: '/centro/$id'
      fullPath: '/centro/$id'
      preLoaderRoute: typeof CentroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentrosRoute: CentrosRoute,
  ImpactoRoute: ImpactoRoute,
  NecesidadesRoute: NecesidadesRoute,
  RegistrarCentroRoute: RegistrarCentroRoute,
  VoluntariosRoute: VoluntariosRoute,
  CentroIdRoute: CentroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
